import { PetAgeUnit } from '@constants/ad/age-unit';
import { FlagType } from '@constants/flag-types';
export class Pagination {
  constructor(
    public pageNumber: number = 1,
    public pageSize: number = 12,
    public searchBy?: string,
    public isService?: boolean,
    public isForSell?: boolean,
    public isDeleted?: boolean,
    public adType?: number,
    public gender?: string,
    public age?: number,
    public ageUnit?: number,
    public minPrice?: number,
    public maxPrice?: number,
    public productBrandId?: number,
    public productCategoryId?: number,
    public countryId?: number,
    public cityId?: number,
    public categoryId?: number,
    public blogCategoryId?: number,
    public subCategoryId?: number,
    public statusId?: number,
    public totalNumbers?: number,
    public sortDateBy?: number,
    public sortPriceBy?: number,
    public shopId?: number,
    public clinicId?: number,
    public petId?: number,
    public productId?: number,
    public flagType?: FlagType,
    public flagValue?: number,
    public currentUserName?: string,
    public receiptUserName?: string,
    public userTimeZone: number = new Date().getTimezoneOffset(),
    public isMobile?: boolean,
  ) {}
  static search(): Pagination {
    return new this(
      1,
      12,
      '',
      false,
      true,
      undefined,
      0,
      '',
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      1,
      0,
    );
  }
}
